<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <UserSecretsId>aspnet-Veiculando.WhiteLabel.Api-A90B666C-DE1C-4688-ADB2-144C4529C5A2</UserSecretsId>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <DefaultItemExcludes>$(DefaultItemExcludes);obj\**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Veiculando\Veiculando.Data\Veiculando.Data.csproj" />
    <ProjectReference Include="..\Veiculando\Veiculando.Infra.IoC\Veiculando.Infra.IoC.csproj" />
    <ProjectReference Include="..\Veiculando\Veiculando.Infra.Security\Veiculando.Infra.Security.csproj" />
    <ProjectReference Include="..\Veiculando\Veiculando.Infra\Veiculando.Infra.csproj" />
    <ProjectReference Include="..\Veiculando\Veiculando.WhiteLabel.Domain\Veiculando.WhiteLabel.Domain.csproj" />
  </ItemGroup>

</Project>
